# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-imageviewer-activity
Version: 10
Release: %mkrel 1
Summary: Image viewer activity for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/ImageViewer/ImageViewer-10.tar.bz2

Requires: sugar-toolkit >= 0.85.3

BuildRequires: gettext  
BuildRequires: sugar-toolkit >= 0.85.3

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Image viewer activity for Sugar.

%prep
%setup -q -n ImageViewer-10


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.ImageViewerActivity

%clean
rm -rf %{buildroot}

%files -f org.laptop.ImageViewerActivity.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc AUTHORS COPYING NEWS

