# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-imageviewer-activity
Version: 14
Release: %mkrel 1
Summary: Image viewer activity for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/ImageViewer/ImageViewer-14.tar.bz2

Requires: sugar-toolkit >= 0.86.1

BuildRequires: gettext  
BuildRequires: sugar-toolkit >= 0.86.0

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Image viewer activity for Sugar.

%prep
%setup -q -n ImageViewer-14


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.ImageViewerActivity

%clean
rm -rf %{buildroot}

%files -f org.laptop.ImageViewerActivity.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc AUTHORS COPYING NEWS

